/**
 * Email delivery utility for weekly safety reports
 * Phase 5: PDF Generation - Plan 02
 *
 * Handles:
 * - Sending professional HTML emails via Resend API
 * - Attaching PDF reports
 * - Including download links with 7-day validity
 * - Graceful degradation if RESEND_API_KEY not configured
 */

interface SendReportEmailParams {
  resendApiKey: string;
  to: string;
  recipientName: string;
  weekEnding: string;
  signedUrl: string;
  pdfBuffer: Uint8Array;
  complianceStatus: string;
  treatmentCount: number;
  nearMissCount: number;
  projectName: string;
  companyName?: string;
}

interface EmailResult {
  success: boolean;
  messageId?: string;
  error?: string;
}

/**
 * Convert Uint8Array buffer to base64 string for email attachment
 */
function bufferToBase64(buffer: Uint8Array): string {
  const binary = Array.from(buffer)
    .map((byte) => String.fromCharCode(byte))
    .join('');
  return btoa(binary);
}

/**
 * Build professional HTML email template
 */
function buildEmailHtml(params: SendReportEmailParams): string {
  const { recipientName, weekEnding, signedUrl, complianceStatus, treatmentCount, nearMissCount, projectName, companyName = 'SiteMedic' } = params;

  const dateStr = weekEnding.split('T')[0]; // YYYY-MM-DD format

  // Color code compliance status
  const statusColor = complianceStatus === 'compliant' ? '#10B981' : complianceStatus === 'at-risk' ? '#F59E0B' : '#EF4444';
  const statusText = complianceStatus === 'compliant' ? 'Compliant' : complianceStatus === 'at-risk' ? 'At Risk' : 'Non-Compliant';

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Weekly Safety Report</title>
</head>
<body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f3f4f6;">
  <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff;">
    <!-- Header -->
    <div style="background-color: #003366; padding: 32px 24px; text-align: center;">
      <h1 style="margin: 0; color: #ffffff; font-size: 28px; font-weight: 600;">${companyName}</h1>
      <p style="margin: 8px 0 0 0; color: #93C5FD; font-size: 14px;">Weekly Safety Report</p>
    </div>

    <!-- Content -->
    <div style="padding: 32px 24px;">
      <!-- Greeting -->
      <p style="margin: 0 0 16px 0; font-size: 16px; color: #111827;">Hello ${recipientName},</p>

      <!-- Summary -->
      <p style="margin: 0 0 24px 0; font-size: 16px; color: #374151; line-height: 1.5;">
        Your weekly safety report for <strong>${projectName}</strong> covering the week ending
        <strong>${dateStr}</strong> is ready.
      </p>

      <!-- Stats Card -->
      <div style="background-color: #f9fafb; border-radius: 8px; padding: 24px; margin-bottom: 24px;">
        <h2 style="margin: 0 0 16px 0; font-size: 18px; color: #111827; font-weight: 600;">Quick Summary</h2>

        <div style="margin-bottom: 12px;">
          <span style="color: #6b7280; font-size: 14px;">Compliance Status:</span>
          <span style="display: inline-block; margin-left: 8px; padding: 4px 12px; background-color: ${statusColor}; color: #ffffff; border-radius: 4px; font-size: 14px; font-weight: 500;">
            ${statusText}
          </span>
        </div>

        <div style="margin-bottom: 8px;">
          <span style="color: #6b7280; font-size: 14px;">Treatment Logs:</span>
          <strong style="margin-left: 8px; color: #111827; font-size: 16px;">${treatmentCount}</strong>
        </div>

        <div>
          <span style="color: #6b7280; font-size: 14px;">Near-Miss Reports:</span>
          <strong style="margin-left: 8px; color: #111827; font-size: 16px;">${nearMissCount}</strong>
        </div>
      </div>

      <!-- Download CTA -->
      <div style="text-align: center; margin-bottom: 24px;">
        <a href="${signedUrl}"
           style="display: inline-block; background-color: #2563EB; color: #ffffff; padding: 14px 32px; border-radius: 6px; text-decoration: none; font-size: 16px; font-weight: 500;">
          Download Full Report (PDF)
        </a>
        <p style="margin: 12px 0 0 0; color: #6b7280; font-size: 12px;">
          This link is valid for 7 days
        </p>
      </div>

      <!-- Footer Note -->
      <div style="border-top: 1px solid #e5e7eb; padding-top: 24px; margin-top: 32px;">
        <p style="margin: 0; color: #6b7280; font-size: 14px; line-height: 1.5;">
          This report was automatically generated by ${companyName}. If you have any questions about the data
          or need assistance, please contact your site medic.
        </p>
      </div>
    </div>

    <!-- Footer -->
    <div style="background-color: #f9fafb; padding: 24px; text-align: center; border-top: 1px solid #e5e7eb;">
      <p style="margin: 0; color: #9ca3af; font-size: 12px;">
        © ${new Date().getFullYear()} ${companyName}. All rights reserved.
      </p>
    </div>
  </div>
</body>
</html>
  `.trim();
}

/**
 * Send weekly safety report email via Resend API
 *
 * @param params - Email parameters including recipient, PDF buffer, and stats
 * @returns Success status and message ID
 */
export async function sendReportEmail(params: SendReportEmailParams): Promise<EmailResult> {
  try {
    const { resendApiKey, to, weekEnding } = params;
    const dateStr = weekEnding.split('T')[0];

    console.log(`📧 Sending report email to ${to}...`);

    // Send email via Resend API
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${resendApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: `${params.companyName || 'SiteMedic'} Reports <reports@sitemedic.co.uk>`,
        to: [to],
        subject: `Weekly Safety Report - Week Ending ${dateStr}`,
        html: buildEmailHtml(params),
        attachments: [
          {
            filename: `weekly-safety-report-${dateStr}.pdf`,
            content: bufferToBase64(params.pdfBuffer),
            content_type: 'application/pdf',
          },
        ],
      }),
    });

    // Check response
    if (!response.ok) {
      const errorBody = await response.text();
      console.error(`❌ Resend API error (${response.status}):`, errorBody);
      return {
        success: false,
        error: `Resend API error: ${response.status} ${errorBody}`,
      };
    }

    const result = await response.json();
    console.log(`✅ Email sent successfully: ${result.id}`);

    return {
      success: true,
      messageId: result.id,
    };
  } catch (error) {
    console.error('❌ Failed to send email:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    };
  }
}
