/**
 * PDF Export Utilities
 *
 * Uses jsPDF + jspdf-autotable for browser-based PDF generation with formatted tables.
 *
 * Research: Pattern 6 from 04-RESEARCH.md - Use jsPDF for formatted reports with page breaks and tables
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import { TreatmentWithWorker } from '@/types/database.types';

/**
 * Export treatments to formatted PDF report
 *
 * Format: A4 landscape with header, formatted table, footer with page numbers
 * Table columns: Date, Worker, Injury Type, Severity, Outcome, RIDDOR
 * Severity column: Color-coded text (green/amber/red)
 */
export function exportTreatmentsPDF(treatments: TreatmentWithWorker[]) {
  // Create A4 landscape PDF document
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Treatment Log Report', 14, 15);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('SiteMedic', 14, 22);
  doc.text(
    `Generated: ${format(new Date(), 'dd/MM/yyyy HH:mm')}`,
    14,
    27
  );

  // Table data
  const tableData = treatments.map((t) => [
    t.created_at ? format(new Date(t.created_at), 'dd/MM/yyyy HH:mm') : '',
    t.worker ? `${t.worker.first_name} ${t.worker.last_name}` : 'Unknown',
    t.injury_type || '',
    t.severity || '',
    formatOutcome(t.outcome),
    t.is_riddor_reportable ? 'Yes' : 'No',
  ]);

  // Generate table with autoTable
  autoTable(doc, {
    startY: 35,
    head: [['Date', 'Worker', 'Injury Type', 'Severity', 'Outcome', 'RIDDOR']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: [30, 41, 59], // #1E293B (dark slate)
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 10,
    },
    bodyStyles: {
      fontSize: 9,
      cellPadding: 3,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252], // #F8FAFC (light gray)
    },
    columnStyles: {
      0: { cellWidth: 35 }, // Date
      1: { cellWidth: 45 }, // Worker
      2: { cellWidth: 50 }, // Injury Type
      3: { cellWidth: 25 }, // Severity
      4: { cellWidth: 45 }, // Outcome
      5: { cellWidth: 20 }, // RIDDOR
    },
    didDrawCell: (data) => {
      // Color-code severity column (index 3)
      if (data.section === 'body' && data.column.index === 3) {
        const severity = tableData[data.row.index][3];
        let color: [number, number, number] = [0, 0, 0]; // default black

        if (severity === 'minor') {
          color = [22, 163, 74]; // green-600
        } else if (severity === 'moderate') {
          color = [245, 158, 11]; // amber-500
        } else if (severity === 'major') {
          color = [239, 68, 68]; // red-500
        } else if (severity === 'critical') {
          color = [185, 28, 28]; // red-700
        }

        doc.setTextColor(color[0], color[1], color[2]);
        doc.text(
          severity,
          data.cell.x + 2,
          data.cell.y + data.cell.height / 2 + 1
        );
        doc.setTextColor(0, 0, 0); // reset to black
      }
    },
    didDrawPage: (data) => {
      // Footer with page number
      const pageCount = doc.getNumberOfPages();
      doc.setFontSize(8);
      doc.setFont('helvetica', 'italic');
      doc.text(
        `Generated by SiteMedic Dashboard - Page ${data.pageNumber} of ${pageCount}`,
        14,
        doc.internal.pageSize.height - 10
      );
    },
  });

  // Download PDF
  doc.save(`treatment-log-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
}

/**
 * Format outcome enum to human-readable string
 */
function formatOutcome(
  outcome:
    | 'returned_to_work'
    | 'sent_home'
    | 'hospital_referral'
    | 'ambulance_called'
    | null
): string {
  if (!outcome) return '';
  const map: Record<string, string> = {
    returned_to_work: 'Returned to Work',
    sent_home: 'Sent Home',
    hospital_referral: 'Hospital Referral',
    ambulance_called: 'Ambulance Called',
  };
  return map[outcome] || outcome;
}
