/**
 * Page Footer Component
 * Phase 5: PDF Generation - Plan 01
 */

import { Text } from 'npm:@react-pdf/renderer@4.3.2';
import { styles } from '../styles.ts';

interface FooterProps {
  projectName: string;
}

export function Footer({ projectName }: FooterProps) {
  return (
    <Text
      style={styles.footer}
      render={({ pageNumber, totalPages }) => (
        `Generated by SiteMedic                Page ${pageNumber} of ${totalPages}                Confidential - ${projectName}`
      )}
      fixed
    />
  );
}
