-- 118: Organisation Settings
-- Created: 2026-02-17
-- Purpose: Store per-organisation business configuration values, replacing
--          hardcoded defaults scattered across the codebase.
--          This migration is the foundation for:
--            - Plan 11-02: Admin settings UI
--            - Plan 11-03: Consumer wiring (pricing, geofencing, urgency premiums)
--
-- Note: No moddatetime trigger added (project convention: manual updated_at in
--       update calls — see migrations 115–117 for this pattern).

-- =============================================================================
-- TABLE: org_settings
-- One row per organisation. Created via INSERT from seed block below.
-- Only platform admins create or delete rows; org users can only read them.
-- =============================================================================

CREATE TABLE org_settings (
  id                      UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  org_id                  UUID          NOT NULL UNIQUE
                          REFERENCES organizations(id) ON DELETE CASCADE,
  base_rate               DECIMAL(10,2) NOT NULL DEFAULT 42.00
                          CHECK (base_rate > 0),
  geofence_default_radius INTEGER       NOT NULL DEFAULT 200
                          CHECK (geofence_default_radius BETWEEN 50 AND 5000),
  urgency_premiums        JSONB         NOT NULL DEFAULT '[0, 20, 50, 75]'::jsonb,
  admin_email             TEXT,
  net30_eligible          BOOLEAN       NOT NULL DEFAULT TRUE,
  credit_limit            DECIMAL(10,2) NOT NULL DEFAULT 5000.00
                          CHECK (credit_limit >= 0),
  created_at              TIMESTAMPTZ   DEFAULT NOW(),
  updated_at              TIMESTAMPTZ   DEFAULT NOW()
);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE org_settings IS
  'Per-organisation business configuration. One row per organisation. '
  'Replaces hardcoded defaults in pricing, geofencing, and urgency logic.';

COMMENT ON COLUMN org_settings.id IS
  'Primary key — UUID generated by uuid_generate_v4().';

COMMENT ON COLUMN org_settings.org_id IS
  'Foreign key to organizations.id. Unique — one settings row per org. '
  'Cascades on organisation deletion.';

COMMENT ON COLUMN org_settings.base_rate IS
  'Hourly base rate in GBP charged to clients. Must be > 0. '
  'Default GBP 42.00 matches the hardcoded default used at v1.0 launch.';

COMMENT ON COLUMN org_settings.geofence_default_radius IS
  'Default site geofence radius in metres (50–5000). '
  'Used when creating a new booking geofence. Default 200 m.';

COMMENT ON COLUMN org_settings.urgency_premiums IS
  'JSONB array of four urgency premium percentages applied based on days '
  'until the shift. Indices: [same-day, 1-day, 2-day, 3-day+]. '
  'Default [0, 20, 50, 75] matches the hardcoded premiums at v1.0 launch.';

COMMENT ON COLUMN org_settings.admin_email IS
  'Primary admin contact email for this organisation. '
  'Used for internal notifications and escalations. NULL = not configured.';

COMMENT ON COLUMN org_settings.net30_eligible IS
  'Whether this organisation''s clients are eligible for Net 30 payment '
  'terms by default. Individual client eligibility may still be overridden '
  'on the clients table. Default TRUE.';

COMMENT ON COLUMN org_settings.credit_limit IS
  'Default credit limit in GBP applied to new Net 30 clients for this org. '
  'Must be >= 0. Default GBP 5000.00.';

COMMENT ON COLUMN org_settings.created_at IS
  'Timestamp when this settings row was first created.';

COMMENT ON COLUMN org_settings.updated_at IS
  'Timestamp of the last settings update. Updated manually by application '
  'update calls (no trigger — project convention).';

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX idx_org_settings_org ON org_settings (org_id);

-- =============================================================================
-- SEED: Backfill settings for all existing organisations
-- Uses ON CONFLICT DO NOTHING so re-running this migration is safe.
-- =============================================================================

INSERT INTO org_settings (
  org_id,
  base_rate,
  geofence_default_radius,
  urgency_premiums,
  admin_email,
  net30_eligible,
  credit_limit
)
SELECT
  id,
  42.00,
  200,
  '[0, 20, 50, 75]'::jsonb,
  NULL,
  TRUE,
  5000.00
FROM organizations
ON CONFLICT (org_id) DO NOTHING;

-- =============================================================================
-- ROW LEVEL SECURITY
-- =============================================================================

ALTER TABLE org_settings ENABLE ROW LEVEL SECURITY;

-- Org users: read their own org's settings (no write — only platform admins mutate)
CREATE POLICY "Org users can view their own org settings"
  ON org_settings FOR SELECT
  USING (org_id = get_user_org_id());

-- Platform admin: full read/write access across all orgs
CREATE POLICY "Platform admins can view all org settings"
  ON org_settings FOR SELECT
  USING (is_platform_admin());

CREATE POLICY "Platform admins can insert org settings"
  ON org_settings FOR INSERT
  WITH CHECK (is_platform_admin());

CREATE POLICY "Platform admins can update all org settings"
  ON org_settings FOR UPDATE
  USING (is_platform_admin())
  WITH CHECK (is_platform_admin());

-- =============================================================================
-- SUMMARY
-- =============================================================================
-- Migration complete: Organisation settings table established.
--
-- Table created:
--   - org_settings (1 index, 2 org-scoped + 3 platform admin = 5 RLS policies total)
--     No DELETE policy for org users — only platform admins create/manage rows.
--
-- Columns:
--   id, org_id, base_rate, geofence_default_radius, urgency_premiums,
--   admin_email, net30_eligible, credit_limit, created_at, updated_at
--
-- Constraints:
--   - UNIQUE (org_id) — one row per organisation
--   - FOREIGN KEY org_id → organizations(id) ON DELETE CASCADE
--   - CHECK base_rate > 0
--   - CHECK geofence_default_radius BETWEEN 50 AND 5000
--   - CHECK credit_limit >= 0
--
-- Seed: All existing organisations back-filled with v1.0 defaults.
--
-- Downstream plans:
--   - 11-02: Admin settings UI reads/writes via org-scoped SELECT + platform admin UPDATE
--   - 11-03: Pricing and geofence logic reads org_settings instead of hardcoded values
