-- 132: Organisation Branding
-- Created: 2026-02-18
-- Purpose: Store per-organisation white-label configuration (logo, primary colour,
--          company name, tagline) used across v3.0 branding features.
--          This migration is the foundation for:
--            - Phase 27: White-label portal (subdomain routing)
--            - Phase 28: Branded PDF reports
--            - Phase 29: Branded email templates
--            - Phase 30: Org branding admin UI
--
-- Note: No moddatetime trigger added (project convention: manual updated_at in
--       update calls — see migrations 115–117 for this pattern).

-- =============================================================================
-- TABLE: org_branding
-- One row per organisation. Created via backfill INSERT below.
-- Platform admins create/manage rows; org admins can update their own row;
-- org users can only read their own row.
-- =============================================================================

CREATE TABLE org_branding (
  id                  UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  org_id              UUID        NOT NULL UNIQUE
                      REFERENCES organizations(id) ON DELETE CASCADE,
  logo_path           TEXT,
  primary_colour_hex  TEXT CHECK (primary_colour_hex IS NULL OR primary_colour_hex ~ '^#[0-9A-Fa-f]{6}$'),
  company_name        TEXT,
  tagline             TEXT,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================================================
-- COMMENTS
-- =============================================================================

COMMENT ON TABLE org_branding IS
  'Per-organisation white-label branding configuration. One row per organisation. '
  'Used by the portal, PDF reports, and email templates in v3.0.';

COMMENT ON COLUMN org_branding.id IS
  'Primary key — UUID generated by uuid_generate_v4().';

COMMENT ON COLUMN org_branding.org_id IS
  'Foreign key to organizations.id. Unique — one branding row per org. '
  'Cascades on organisation deletion.';

COMMENT ON COLUMN org_branding.logo_path IS
  'Supabase Storage path to the organisation logo file. '
  'NULL until the org uploads a logo. Resolved to a signed URL at render time.';

COMMENT ON COLUMN org_branding.primary_colour_hex IS
  'Primary brand colour as a 6-digit hex string including leading # (e.g. #1A2B3C). '
  'NULL until configured. CHECK constraint enforces ^#[0-9A-Fa-f]{6}$ format. '
  'NULL is allowed (initial state for all orgs).';

COMMENT ON COLUMN org_branding.company_name IS
  'Display name for the organisation used in white-label contexts (portal header, '
  'PDFs, emails). Pre-populated from organizations.name at migration time.';

COMMENT ON COLUMN org_branding.tagline IS
  'Optional marketing tagline displayed below the logo on the white-label portal. '
  'NULL until configured by the org admin.';

COMMENT ON COLUMN org_branding.created_at IS
  'Timestamp when this branding row was first created.';

COMMENT ON COLUMN org_branding.updated_at IS
  'Timestamp of the last branding update. Updated manually by application '
  'update calls (no trigger — project convention).';

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX idx_org_branding_org ON org_branding (org_id);

-- =============================================================================
-- SEED: Backfill branding rows for all existing organisations
-- Carries over organizations.name into company_name so every org has a
-- meaningful display name without further admin action.
-- Uses ON CONFLICT DO NOTHING so re-running this migration is safe.
-- =============================================================================

INSERT INTO org_branding (org_id, company_name)
SELECT id, name
FROM organizations
ON CONFLICT (org_id) DO NOTHING;

-- =============================================================================
-- ROW LEVEL SECURITY
-- =============================================================================

ALTER TABLE org_branding ENABLE ROW LEVEL SECURITY;

-- Org users: read their own org's branding (no write for regular users)
CREATE POLICY "Org users can view their own org branding"
  ON org_branding FOR SELECT
  USING (org_id = get_user_org_id());

-- Org admins: update their own org's branding row
CREATE POLICY "Org admins can update their own org branding"
  ON org_branding FOR UPDATE
  USING (org_id = get_user_org_id() AND is_org_admin())
  WITH CHECK (org_id = get_user_org_id() AND is_org_admin());

-- Platform admin: full read/write access across all orgs
CREATE POLICY "Platform admins can view all org branding"
  ON org_branding FOR SELECT
  USING (is_platform_admin());

CREATE POLICY "Platform admins can insert org branding"
  ON org_branding FOR INSERT
  WITH CHECK (is_platform_admin());

CREATE POLICY "Platform admins can update all org branding"
  ON org_branding FOR UPDATE
  USING (is_platform_admin())
  WITH CHECK (is_platform_admin());

-- =============================================================================
-- SUMMARY
-- =============================================================================
-- Migration complete: Organisation branding table established.
--
-- Table created:
--   - org_branding (1 index, 2 org-scoped + 3 platform admin = 5 RLS policies total)
--     No DELETE policy for org users — only platform admins manage row lifecycle.
--
-- Columns:
--   id, org_id, logo_path, primary_colour_hex, company_name, tagline,
--   created_at, updated_at
--
-- Constraints:
--   - UNIQUE (org_id) — one row per organisation
--   - FOREIGN KEY org_id → organizations(id) ON DELETE CASCADE
--   - CHECK primary_colour_hex IS NULL OR primary_colour_hex ~ '^#[0-9A-Fa-f]{6}$'
--
-- Seed: All existing organisations back-filled with company_name from organizations.name.
--       logo_path, primary_colour_hex, and tagline default to NULL.
--
-- RLS policies (5 total):
--   1. Org users can view their own org branding        (SELECT, org-scoped)
--   2. Org admins can update their own org branding     (UPDATE, org-scoped + is_org_admin())
--   3. Platform admins can view all org branding        (SELECT, platform-wide)
--   4. Platform admins can insert org branding          (INSERT, platform-wide)
--   5. Platform admins can update all org branding      (UPDATE, platform-wide)
--
-- Downstream plans:
--   - Phase 27: White-label portal reads logo_path, primary_colour_hex, company_name, tagline
--   - Phase 28: PDF report generator reads company_name and logo_path
--   - Phase 29: Email templates read company_name and logo_path
--   - Phase 30: Org branding admin UI reads/writes via org admin UPDATE policy
